### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by 31Pratishtha** [mohammadruman/KiitFood#1]
Change the repo name from KiitFood to Kampus-Eats or KampusEats.

**Comment by mohammadruman** [comment]
Thank you for the suggestion, @31Pratishtha , I'll proceed with renaming the repository to "Kampus-Eats" (or "KampusEats," depending on the team's preference). 

Please let me know if there's anything else you'd like to adjust.

**Comment by mohammadruman** [comment]
Thank you for the suggestion, @31Pratishtha , I'll proceed with renaming the repository to "Kampus-Eats" (or "KampusEats," depending on the team's preference).

Please let me know if there's anything else you'd like to adjust.
